"""video

Revision ID: 2b87a9e14570
Revises: 
Create Date: 2021-05-05 12:58:05.296103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b87a9e14570'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('band',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('formation', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_band_formation'), 'band', ['formation'], unique=False)
    op.create_index(op.f('ix_band_name'), 'band', ['name'], unique=False)
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=True),
    sa.Column('genre', sa.String(length=15), nullable=True),
    sa.Column('songs', sa.Integer(), nullable=True),
    sa.Column('band_id', sa.Integer(), nullable=True),
    sa.Column('avaibility', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['band_id'], ['band.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_genre'), 'video', ['genre'], unique=False)
    op.create_index(op.f('ix_video_songs'), 'video', ['songs'], unique=False)
    op.create_index(op.f('ix_video_title'), 'video', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_title'), table_name='video')
    op.drop_index(op.f('ix_video_songs'), table_name='video')
    op.drop_index(op.f('ix_video_genre'), table_name='video')
    op.drop_table('video')
    op.drop_index(op.f('ix_band_name'), table_name='band')
    op.drop_index(op.f('ix_band_formation'), table_name='band')
    op.drop_table('band')
    # ### end Alembic commands ###
