"""table

Revision ID: 3397d76d2810
Revises: 
Create Date: 2021-04-06 16:10:25.406826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3397d76d2810'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('band',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('band_name', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_band_band_name'), 'band', ['band_name'], unique=False)
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=True),
    sa.Column('genre', sa.String(length=15), nullable=True),
    sa.Column('songs', sa.Integer(), nullable=True),
    sa.Column('band_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['band_id'], ['band.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_genre'), 'video', ['genre'], unique=False)
    op.create_index(op.f('ix_video_songs'), 'video', ['songs'], unique=False)
    op.create_index(op.f('ix_video_title'), 'video', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_title'), table_name='video')
    op.drop_index(op.f('ix_video_songs'), table_name='video')
    op.drop_index(op.f('ix_video_genre'), table_name='video')
    op.drop_table('video')
    op.drop_index(op.f('ix_band_band_name'), table_name='band')
    op.drop_table('band')
    # ### end Alembic commands ###
